#-------------------------
#GItHub Action Part-1-Basic
#
#Copyleft (c) by Denis Astahov 2019
#------------------------
Исправленный файл my-basic.yml без использования неправильных символов и тегов от Google:

name: My-GitHubAction-Basics
on:
  push:
    branches:
      master
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      name: Print Hello Message
        run: echo "Hello world from Testing job"
  my_deploy:
    runs-on: ubuntu-latest
    steps:
      name: Print Hello Message
        run: echo "Hello world from Deploy job"
